version: 0.0
os: linux
files:
  - source: /
    destination: /app
permissions:
  - object: script/start.sh
    mode: 755
    type:
      - file
  - object: script/stop.sh
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: script/stop.sh
  ApplicationStart:
    - location: script/start.sh
