version: 0.0
os: linux
files:
  - source: script
    destination: /app/script
  - source: bin
    destination: /app/bin
  - source: pom.xml
    destination: /app/pom.xml
  - source: project.clj
    destination: /app/project.clj
  - source: public
    destination: /app/public
  - source: src
    destination: /app/src
  - source: system.properties
    destination: /app/system.properties
  - source: templates
    destination: /app/templates
hooks:
  BeforeInstall:
    - location: script/stop.sh
    - location: script/clean.sh
  ApplicationStart:
    - location: script/start.sh
