  <div class="sidebar col-md-2">
    <div class="sidebar-content">
      <h4>about</h4>
      <p>
        This is Chris Zelenak's personal blog. I work at <a href="http://fastestforward.com/">Fastest Forward</a> on consulting and our product, <a href="https://instrumentalapp.com/">Instrumental</a>. This blog is served via a personal project using <a href="http://clojure.org/">Clojure</a> and <a hreff="http://netty.io">Netty</a>, and is <a href="https://bitbucket.org/netshade/yetifactory-clj">open source</a>.
      </p>
      <a href="https://github.com/netshade"><img src="/github48.png" /></a>
      <a href="https://twitter.com/netshade"><img src="/twitter48.png" /></a>
    </div>
  </div>
